kind: Service
apiVersion: v1
metadata:
  name: halo
  labels:
    app: halo
spec:
  type: ClusterIP
  selector:
    app: halo
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: halo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halo
  template:
    metadata:
      labels:
        app: halo
        version: v1
    spec:
      containers:
      - name: halo
        image: halo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
