dubbo:
  application:
    name: dubbo-springboot-demo-idl-provider
    logger: slf4j
    enable-file-cache: false
    qos-enable: false
  protocol:
    name: tri
    port: 50052
  registry:
    address: nacos://${nacos.address:127.0.0.1}:8848?username=nacos&password=nacos