
logging.level.org.springframework.jdbc.core.JdbcTemplate: debug

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect
  show-sql: true
  pretty-sql: true
  database-validation-mode: ERROR



